spring.application.name=seap-agent

server.port=8001


#embabel.models.defaultLlm=gemini-2.5-flash
embabel.models.defaultLlm=gemini-2.5-flash
#embabel.models.defaultLlm=gemini-3-flash-preview
#embabel.models.defaultLlm=gemini-3-pro-preview
#embabel.models.defaultLlm=gemini-3-pro-preview
#embabel.models.defaultLlm=gemini-2.5-flash
#embabel.models.defaultLlm=gemini-3-flash


#spring.ai.openai.api-key={GEMINI_API_KEY}
#spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai

#spring.ai.openai.embedding.options.model=gemini-embedding-001
#spring.ai.openai.embedding.embeddings-path=/embeddings
#spring.ai.openai.embedding.options.dimensions=768

OPENAI_BASE_URL=https://generativelanguage.googleapis.com/v1beta/openai

#seap-tests
#OPENAI_API_KEY=AIzaSyCEE_YFZHP87rN3uRLO6LLQmYvvA-RApaE

# My First Project
#OPENAI_API_KEY=AIzaSyBWS8a5uZtgIoY2Ord0RQ4ajq03DeF1RoA

# useMCPgdrive
#OPENAI_API_KEY=AIzaSyASYYE_xDRMDexl_oOCbHk85zQIdLcm7no

# last-random-test
#OPENAI_API_KEY=AIzaSyA9btj_PFhoTQBW0Ca3LMLvSpbK_Z9NYIg

#seap-search-api
OPENAI_API_KEY=AIzaSyDQskKO2NadOfzu7P-8LKXZAtJ7qUuwCiM

#gemini-api
#OPENAI_API_KEY=AIzaSyDAD5Ld0N9L61Ga-ASXEhUrWuWbP9lB_8M

# seap-agent-article
#OPENAI_API_KEY=AIzaSyB1S_JEVwIYNYGtrlDhR5Jsm6K1AGw5qGU

# seap-key-01
#OPENAI_API_KEY=AIzaSyDB3PKHZHSneallFEEMKMySVp9UV2C5-yo
#OPENAI_API_KEY=AIzaSyDGE3H0tXxhGlzZK_qMA7O1GUv1JdQ4qfA


#OPENAI_API_KEY=AIzaSyD8WZHqTrVQuuiuszalnwM-FvzQWURVPEE

# seap-key-02
#OPENAI_API_KEY=AIzaSyDiVIX_yahv8KNgx3q2PPgTPGInMlECUNA

# seap-key-03




gemini.models.chat.name=gemini-2.5-flash-lite
OPENAI_COMPLETIONS_PATH=/chat/completions


# postgres configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/contratos_pdf
spring.datasource.username=admin
spring.datasource.password=adminpass
